### Request prediction
# @name predict
POST http://localhost:8000/prediction
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="a.png"
Content-Type: image/png

< ../samples/a.png
--MyBoundary--

### Get prediction result
@prediction_id = {{predict.response.body.prediction_id}}

GET http://localhost:8000/prediction/{{prediction_id}}
